name: isopy
channels: 
    - conda-forge
    - defaults
dependencies: 
    - python=3.7    # Python version 3.7
    - bottleneck    # C-optimized array functions for NumPy
    - cython        # Transpile Python->C
    - dask          # Parallel processing library
    - future        # Python 2/3 compatibility
    - ipython       # IPython interpreter and tools
    - jupyter       # Jupyter federation architecture
    - matplotlib    # 2D plotting library
    - netcdf4       # Wrapper for netcdf4
    - notebook      # Notebook interface
    - numpy         # N-d array and numerics
    - scipy         # Common math/stats/science functions
    - statsmodels   # Regression/modeling toolkit
    - six           # Python 2/3 compatibility
    - tqdm          # Nice progressbar for longer computations
    - xarray        # N-d labeled array library
